assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/', include('task.urls')),
    path('task/', include('django.contrib.auth.urls')),
]

task/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
app_name = 'task'
urlpatterns = [
	path('login/', auth_views.login, name='login'),
	path('logout/', auth_views.logout, name='logout'),
	url(r'^home/$', TemplateView.as_view(template_name='task/home.html'), name='home'),
	url(r'^create/$', views.create, name='create'),
	url(r'^search/$', views.usersearch, name='usersearch'),
	url(r'^commits/(?P<repo_name>\w.+)/$', views.usercommit, name='usercommit'),
]

task/models.py
from django.db import models

task/forms.py
from django import forms

class APIform(forms.Form):
	g_username = forms.CharField(max_length=30, label='GitHub Username', required = False)

task/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .forms import APIform
from django.views import generic
from django.http import HttpResponse
import requests
import json

def create(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('task:home')
	else:
		form = UserCreationForm()
	return render(request, 'task/create.html', {'form': form})

def usersearch(request):     #https://simpleisbetterthancomplex.com/tutorial/2018/02/03/how-to-use-restful-apis-with-django.html
	if request.user.is_authenticated:
		if request.method == 'GET':
			form = APIform(request.GET)
			if form.is_valid():
				git_username = form.cleaned_data.get('g_username')
				r = requests.get("https://api.github.com/users/%s"%git_username)
				r1 = requests.get("https://api.github.com/users/%s/repos"%git_username)
				repo = r1.json()
				repol = []

				for repos in repo:
					if isinstance(repos,dict):      #Used isinstance To Remove Type Error
						repol.append((repos["name"],repos["language"]))

				if r.status_code == 200:
					found = True
				else:
					found = False

				request.session['git_username'] = git_username
				return render(request, 'task/search.html', {'git_username':git_username, 'found':found, 'form':form, 'repol':repol})
		else:
			form = APIform()
		return render(request, 'task/search.html',{'form':form, 'found':False})
	else:
		return render(request, 'task/home.html')

def usercommit(request, repo_name):
	if request.user.is_authenticated:
		git_username = request.session['git_username']
		r = requests.get("https://api.github.com/repos/%s/%s/commits" %(git_username,repo_name))
		s = r.json()
		commitl = []

		for commits in s:
			if isinstance(commits,dict):
				commitl.append((commits["commit"]["author"]["date"],commits["commit"]["message"]))
		return render(request, 'task/commits.html', {'commitl':commitl, 'git_username':git_username, 'repo_name':repo_name})
	else:
		return render(request, 'task/home.html')

task/templates/task/base.html
{% load staticfiles %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'task:home' %}"><i class="fa fa-github-square"></i>Unicode</a>
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'task:usersearch' %}" ><i class="fa fa-search"></i>Search</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item"> 
                        <a class="nav-link" href=""><i class="fa fa-user-circle-o">{{user.username}}</i> |</a>
                    </li>
                    <li class="nav-item">
                    	<a class="nav-link" href="{% url 'logout' %}" ><i class="fa fa-sign-out"></i>Log Out</a>
                    </li>
                </ul>
            {% else %}
            	<ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                    	<a class="nav-link" href="{% url 'login' %}" ><i class="fa fa-sign-in"></i>Log In</a>
                    </li>
                    <li class="nav-item">
                    	<a class="nav-link" href="{% url 'task:create' %}" ><i class="fa fa-pencil-square-o"></i>Sign Up</a>
                    </li>
                </ul>
            {% endif %}
</nav>
	{% block body %}
    {% endblock %}
</body>

task/templates/task/commits.html
{% extends 'task/base.html' %}
{% block body %}
<div class="container">
	<h3><u>{{git_username}}</u> Your Commits for <u>{{repo_name}}</u> Are:</h3>
	<br>
	<p></p>
	{% for i in commitl %}
	<b>Message:</b> {{i.1}}
	<br>
	<b>Date:</b> {{i.0}}
	<br>
	<br>
	{% empty %}
	No Commit History Found!!<br>
	<b>Zero</b> Commits
	{% endfor %}
</div>
{% endblock %}

task/templates/task/create.html
{% extends 'task/base.html' %}
{% block body %}
<div class="container">
<h2>Sign Up</h2>
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn-primary">Sign Up</button>
</form>
</div>
{% endblock %}

task/templates/task/home.html
{% extends 'task/base.html' %}
{% block body %}
<div class="container">
{% if user.is_authenticated %}
<br>
<h3 style="text-align: center;">Hi {{ user.username }}!!</h3>
<h6 style="text-align: center;">You Are Good To Go Now</h6>
{% else %}
<br>
<h3 style="text-align: center;">Welcome To The DJ Unicode Page!!</h3>
<br>
<h5 style="text-align: center;">You Must Be Logged In To Get Started</h5>
<h5 style="text-align: center;">If You Are Not A User You Can Sign Up</h5>
{% endif %}
</div>
{% endblock %}

task/templates/task/search.html
{% extends 'task/base.html' %}
{% block body %}
<div class="container">
	<br>
	<form method="GET">
	{% csrf_token %}
    {{ form }}
    <!--<input type="submit" value="Search" class="btn btn-primary" />-->
    <button class="btn btn-primary"><i class="fa fa-search"></i></button>
	</form>
	{% if found %}
		<h3>Hello {{git_username}}</h3>
		<h5>Your Repositories are : </h5>
		<ol>
			{% for repo in repol %}
			<li>
				Name: <a href="{% url 'task:usercommit' repo.0 %}">{{repo.0}}</a>
				<br>
				Language: {{repo.1}}
			</li>
			{% endfor %}
		</ol>
	{% elif git_username != '' %}
		<h4>No Such User Exist</h4>
	{% endif %}
</div>
{% endblock %}